import streamlit as st
import google.generativeai as genai
import tempfile
import os

# --- 1. SETUP API KEY SAFELY ---
# We initialize the variable first to avoid the NameError
API_KEY = None

# First, try to get it from the Cloud Secrets (or local secrets.toml)
if "GEMINI_API_KEY" in st.secrets:
    API_KEY = st.secrets["GEMINI_API_KEY"]

# --- SIDEBAR CONFIGURATION ---
with st.sidebar:
    st.image("https://moneyplus.in/wp-content/uploads/2019/01/moneyplus-logo-3-300x277.png", width=100)
    st.title("Settings")
    
    # If the key wasn't found in secrets, ask for it here
    if not API_KEY:
        API_KEY = st.text_input("Enter Gemini API Key", type="password")
        if not API_KEY:
             st.warning("⚠️ Please enter your API Key to continue.")
    else:
        # If it was found in secrets, just show a success message
        st.success("API Key Loaded Securely")

    st.info("Upload a Discharge Summary to generate an audit report.")

# --- CONFIGURE GEMINI ---
if API_KEY:
    genai.configure(api_key=API_KEY)

# --- MAIN PAGE UI ---
st.title("Moneyplus Discharge Summary Auditor")
st.markdown("Submit the claim intimation number and upload the PDF below.")

# Custom CSS for the Report
st.markdown("""
    <style>
    .report-container {
        border: 1px solid #ddd;
        padding: 25px;
        border-radius: 10px;
        background-color: #ffffff;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        color: #333;
        font-family: sans-serif;
    }
    .report-header {
        border-bottom: 2px solid #0056b3;
        padding-bottom: 10px;
        margin-bottom: 20px;
        color: #0056b3;
    }
    .section-title {
        background-color: #f4f4f4;
        padding: 8px 12px;
        border-left: 5px solid #0056b3;
        color: #0056b3;
        margin-top: 20px;
        font-weight: bold;
    }
    .info-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 15px;
    }
    .info-table td {
        padding: 8px;
        border-bottom: 1px solid #eee;
    }
    .highlight-box {
        background-color: #eef6fc;
        border: 1px solid #cce5ff;
        padding: 15px;
        border-radius: 5px;
    }
    </style>
""", unsafe_allow_html=True)

# Input Form
col1, col2 = st.columns([1, 2])
with col1:
    claim_id = st.text_input("Claim Intimation No.", placeholder="e.g. CLM-2025-001")
with col2:
    uploaded_file = st.file_uploader("Upload Discharge Summary", type=["pdf"])

# --- PROCESSING LOGIC ---
if st.button("Generate Audit Report", type="primary"):
    if not API_KEY:
        st.error("🚨 API Key is missing. Please check your secrets or sidebar input.")
    elif not uploaded_file:
        st.error("Please upload a PDF file first.")
    elif not claim_id:
        st.warning("Please enter a Claim ID.")
    else:
        with st.spinner("Reading document and generating report..."):
            try:
                # 1. Save uploaded file to temp
                with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                    tmp_file.write(uploaded_file.getvalue())
                    tmp_file_path = tmp_file.name

                # 2. Upload to Gemini
                model = genai.GenerativeModel("gemini-2.5-flash")
                sample_file = genai.upload_file(path=tmp_file_path, display_name="Claim Doc")

                # 3. Define Prompt
                prompt = f"""
                You are a Medical Claims Auditor for Moneyplus. Analyze this discharge summary for Claim ID: {claim_id}.
                
                Create a HTML report using EXACTLY this structure. Do not use Markdown ticks.
                
                <div class="report-container">
                    <div class="report-header">
                        <h2 style="margin:0;">Clinical Audit Summary</h2>
                        <small>Generated by Moneyplus AI • Claim #{claim_id}</small>
                    </div>

                    <div class="section-title">Patient Details</div>
                    <table class="info-table">
                        <tr>
                            <td width="30%"><strong>Name:</strong></td>
                            <td>{{INSERT_PATIENT_NAME}}</td>
                        </tr>
                        <tr>
                            <td><strong>Age / Gender:</strong></td>
                            <td>{{INSERT_AGE}} / {{INSERT_GENDER}}</td>
                        </tr>
                        <tr>
                            <td><strong>Admission Date:</strong></td>
                            <td>{{INSERT_DOA}}</td>
                        </tr>
                        <tr>
                            <td><strong>Discharge Date:</strong></td>
                            <td>{{INSERT_DOD}}</td>
                        </tr>
                    </table>

                    <div class="section-title">Clinical Analysis</div>
                    <div class="highlight-box">
                        <p><strong>Primary Diagnosis:</strong> {{INSERT_DIAGNOSIS}}</p>
                        <p><strong>Procedure/Treatment:</strong> {{INSERT_TREATMENT_SUMMARY}}</p>
                    </div>

                    <div class="section-title">Audit Flags</div>
                    <ul style="margin-top:10px;">
                        <li><strong>Room Category:</strong> {{INSERT_ROOM_CATEGORY}}</li>
                        <li><strong>Comorbidities:</strong> {{INSERT_COMORBIDITIES}}</li>
                    </ul>
                    
                    <div style="margin-top: 20px; font-size: 0.8em; color: #777; text-align: center;">
                        Disclaimer: This report is AI-generated. Verify with original documents.
                    </div>
                </div>
                """

                # 4. Generate Content
                response = model.generate_content([sample_file, prompt])
                
                # Clean up
                clean_html = response.text.replace("```html", "").replace("```", "")

                # 5. Display Result
                st.markdown("---")
                st.markdown(clean_html, unsafe_allow_html=True)

                # 6. Add Download Button
                st.download_button(
                    label="📥 Download Report as HTML",
                    data=clean_html,
                    file_name=f"Audit_Report_{claim_id}.html",
                    mime="text/html"
                )

                os.remove(tmp_file_path)

            except Exception as e:
                st.error(f"An error occurred: {e}")
